### 로컬 테스트 서버 루트
GET {{base}}/

### JSON 응답 (httpbin 스타일 echo)
# @name echo
GET {{base}}/demo.json
X-Trace-Id: {{$guid}}
X-Requested-At: {{$datetime iso8601}}

### 요청 변수 체이닝: echo를 먼저 보내면 응답 값이 헤더로 들어간다
GET {{base}}/demo.json
X-From-Previous: {{echo.response.body.$.hello}}
